### ISSUE TITLE
Wget returns 403 forbidden

### ISSUE THREAD

**Issue by RiversideRocks** [tb0hdan/domains#11]
(same issue as https://github.com/tb0hdan/domains/issues/5)

Hey, I'm including one of the datasets in my script. I'm using Python's wget package (which uses the standard wget user agent) and Cloudflare gives me a 403 error.

```
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

**Comment by elliotwutingfeng** [comment]
I don't think tb0hdan is likely to reply anytime soon, given that his country is under siege by Russia.

**Comment by RiversideRocks** [comment]
I think I'm going to use a different library, Cloudflare is very weird about their user agents. @tb0hdan, I hope you are doing alright!
