### ISSUE TITLE
French domain names from public orgs

### ISSUE THREAD

**Issue by JulienPalard** [tb0hdan/domains#14]
Hi!

You may be interested by this dataset: https://github.com/etalab/noms-de-domaine-organismes-publics

If I get my shell-fu right (`comm -13 theirs mine | wc -l`), it may contain 22673 domains that you don't have, it's "small" as it only contains domains from public orgs (and you already have a lot from AFNIC open data), but it's probably worth it?

**Comment by tb0hdan** [comment]
Added. Scanned on a daily basis
