### ISSUE TITLE
Domain dataset source: ICANN Centralized Zone Data Service (CZDS)

### ISSUE THREAD

**Issue by elliotwutingfeng** [tb0hdan/domains#18]
**ICANN (Internet Corporation for Assigned Names and Numbers)** provides a [Centralized Zone Data Service (CZDS)](https://czds.icann.org) where you can request free access to the [Zone Files](https://czds.icann.org/help#zone-files) provided by participating [generic Top-Level Domains (gTLDs)](https://www.icann.org/icann-acronyms-and-terms/en/G0169).

Currently there are over 1100 generic TLDs (including the big ones like **com**, **net**, **org**) available for download (terms-of-service limit: maximum of one download per 24 hours per zonefile).

_You can scrape your domains from the zonefiles._

---

You will need to provide a request "reason" to each zonefile registrar.

From my experience, most (>98%) registrars expect the following information (a handful will reject your access request if any of the following information is omitted):

- Name
- Email
- IP Address
- Physical Address (Building, Street, Postcode etc.)
- Phone Number
- Reason (what you intend to do with the zonefiles)

---

It is also possible to automatically request zonefile access rights and download zonefiles via the [ICANN CZDS API](https://github.com/icann/czds-api-client-python) instead of from the website user interface.

**Comment by tb0hdan** [comment]
@elliotwutingfeng I cannot directly import CZDS data due to licensing restrictions. I can use it for crawling purposes, however. Thanks for this.
