### ISSUE TITLE
If you are only searching domains, why is your crawler scraping pages???

### ISSUE THREAD

**Issue by Jas0n99** [tb0hdan/domains#2]
1. It doesn't appear that your crawler checks for a robots.txt before crawling a site. This is BAD practice if you want to be a 'legitimate' bot. Some sites do NOT want to be crawled by random bots, or there are pages you shouldn't be crawling (for various reasons)...

2. You appear to have ZERO rate limiting for your crawl speed. That is ABUSE... I count 40 PAGES/sec request rate (and that doesn't include other content)...

**Comment by tb0hdan** [comment]
0. Pages are scraped to collect links within site itself.
1. Indeed, there's no `robots.txt` check yet. I'll have it added soon.
2. Adding rate limiting defeats whole purpose of domain collection. Sites are indexed as quickly as possible and revisited not sooner that 1 month.

**Comment by taladar** [comment]
What you are essentially doing is running a DoS bot on any webserver that is not able to keep up with your rate of requests.

**Comment by stlvc** [comment]
Friendly reminder - people are getting paid by other people to analyze why the heck their websites are getting shut down. So your bot is responsible for burning money - one of our customers is directly affected. Please reconsider your approach. You're hurting smaller businesses with this.

**Comment by tb0hdan** [comment]
All crawling activities has been stopped until load issue is fixed.

**Comment by tb0hdan** [comment]
Short update:

- Amount of concurrent requests was decreased 8 times
- Random delay was increased to 60 seconds
- Robots.txt is now parsed and tested for `/` and any other URL that occurs on a website
- Limits were checked on several servers that I have access to

Crawling activities will be restored carefully and gradually.
This issue will remain open for some time in case something goes wrong with this new functionality.

**Comment by tb0hdan** [comment]
Well, it's been almost a month already with no apparent issues. Marking this issue as closed.

**Comment by ciencia** [comment]
This is a small excerpt of my access log where I've found lots of concurrent requests on the exact same second:

https://gist.github.com/ciencia/dece9b00294468ef002171eb0e8d7a37

No robots.txt access.

Of course, I'm now blocking your bot from accessing our website, and report it to all sites tracking abusing bots

**Comment by aivarsi** [comment]
Experiencing the same issue as ciencia. Loads of concurrent sudden requests, robots.txt not being accessed.
