### ISSUE TITLE
Please specifiy your crawler User-agent for robots.txt

### ISSUE THREAD

**Issue by DamonHD** [tb0hdan/domains#28]
It does not appear to be documented, and your crawler is wasting lots of bandwidth downloading lots of media files that do not contain any URL metadata.

**Comment by tb0hdan** [comment]
Thank you so much for that, I'll have it fixed before resuming crawling process.

**Comment by DamonHD** [comment]
Do also please explicitly document which User-agent you respond to in robots.txt!

Thanks for responding quickly.

Rgds

Damon

**Comment by tb0hdan** [comment]
Fixed + doc: https://github.com/tb0hdan/domains/blob/master/README.md#disabling-domains-project-bot-access-to-your-website
