### ISSUE TITLE
Certificate Transparency Data?

### ISSUE THREAD

**Issue by p0lr** [tb0hdan/domains#9]
This seems like a good source of data for your use case.
Every SSL certificate (including subject and subject alternate names) gets written to a log.  You can read the logs and extract the domains.

https://certificate.transparency.dev/

Might even be able to use the stream from Cali Dog Security to feed you the data to parse and build onto your data set:

https://certstream.calidog.io/

**Comment by tb0hdan** [comment]
Hi @p0lr, 

This is actually an excellent proposal. I've tested stream from Cali Dog, it yields about 18 million domains per day. I can make it 3-10 times more just by issuing DNS probes. Furthermore, I'm not saying that all of 180 million can be added to existing dataset, but still superb.

**Comment by tb0hdan** [comment]
Cert stream is used regularly. Closing issue as resolved.
